redis-db:
  restart: always
  command: redis-server --appendonly yes
  labels:
    io.rancher.container.hostname_override: container_name
  tty: true
  image: redis:3.0.3
  stdin_open: true

clouddriver-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
clouddriver-app:
  restart: always
  labels:
    io.rancher.sidekicks: clouddriver-config
    io.rancher.container.hostname_override: container_name
  image: spinnaker/clouddriver
  links:
    - redis-db
  ports:
    - 7002
  volumes_from:
    - clouddriver-config

front50-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
front50-app:
  restart: always
  labels:
    io.rancher.sidekicks: front50-config
    io.rancher.container.hostname_override: container_name
  environment:
    JAVA_OPTS: -javaagent:/opt/front50/lib/jamm-0.2.5.jar
  image: spinnaker/front50
  ports:
    - 8080
  external_links:
  - ${cassandra_target_link}:cassandra-db
  volumes_from:
    - front50-config

igor-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
igor-app:
  restart: always
  labels:
    io.rancher.sidekicks: igor-config
    io.rancher.container.hostname_override: container_name
  image: spinnaker/igor
  links:
    - redis-db
    - echo-app
  ports:
    - 8088
  volumes_from:
    - igor-config

echo-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
echo-app:
  restart: always
  labels:
    io.rancher.sidekicks: echo-config
    io.rancher.container.hostname_override: container_name
  environment:
    JAVA_OPTS: -javaagent:/opt/echo/lib/jamm-0.2.5.jar
  image: spinnaker/echo
  ports:
    - 8089
  volumes_from:
    - echo-config
  external_links:
  - ${cassandra_target_link}:cassandra-db
  links:
    - orca-app
    - front50-app

deck-ui:
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
    API_HOST: spinnaker-api.devops.connectedfleet.io
    DECK_HOST: 0.0.0.0
    DECK_PORT: 9000
    PROTOCOL: http
    AUTH: false
  image: spinnaker/deck
  ports:
    - 9000
  links:
    - gate-app

gate-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
gate-app:
  restart: always
  labels:
    io.rancher.sidekicks: gate-config
    io.rancher.container.hostname_override: container_name
  image: spinnaker/gate
  links:
    - redis-db
    - clouddriver-app
    - echo-app
    - front50-app
    - igor-app
    - orca-app
  ports:
    - 8084
  volumes_from:
    - gate-config

orca-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
orca-app:
  restart: always
  labels:
    io.rancher.sidekicks: orca-config
    io.rancher.container.hostname_override: container_name
  image: spinnaker/orca
  links:
    - redis-db
    - clouddriver-app
    - echo-app
    - front50-app
    - igor-app
  ports:
    - 8083
  volumes_from:
    - orca-config

rosco-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
rosco-app:
  restart: always
  labels:
    io.rancher.sidekicks: rosco-config
    io.rancher.container.hostname_override: container_name
  image: spinnaker/rosco
  environment:
    REDIS_URL: redis://redis-db:6379
  ports:
    - 8087
  volumes_from:
    - rosco-config
  links:
    - redis-db
    - rush-app

rush-config:
  image: objectpartners/spinnaker-config:latest
  restart: always
rush-app:
  restart: always
  labels:
    io.rancher.sidekicks: rush-config
    io.rancher.container.hostname_override: container_name
  environment:
    JAVA_OPTS: -javaagent:/opt/rush/lib/jamm-0.2.5.jar
  image: spinnaker/rush
  ports:
    - 8085
  external_links:
  - ${cassandra_target_link}:cassandra-db
  volumes_from:
    - rush-config
